<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{promo_code}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PromoCode".
 *
 * Columns in table "{{promo_code}}" available as properties of the model,
 * followed by relations of table "{{promo_code}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $code
 * @property string $discount
 * @property string $expiry_date
 * @property integer $state_id
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 *
 * @property User $createUser
 * @property PromoProduct[] $promoProducts
 */
abstract class BasePromoCode extends ActiveRecord {
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Active",
				"Closed" 
		);
		if ($id === null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id % count ( $list )];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id === null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id % count ( $list )];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = date ( 'Y-m-d H:i:s' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{promo_code}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'promo code|promo codes', $n );
	}
	public static function representingColumn() {
		return 'title';
	}
	public function rules() {
		return array (
				array (
						'title,  code, discount, create_time, create_user_id,expiry_date',
						//'expiry_date',
						'required' 
				),
				array (
						'code',
						'unique' 
				),
				array (
						'state_id,discount, type_id, create_user_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'title, code, discount',
						'length',
						'max' => 255 
				),
				array (
						'expiry_date',
						'safe' 
				),
				array (
						'expiry_date, state_id, type_id',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, title, description, code, discount, expiry_date, state_id, type_id, create_time, create_user_id',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'promoProducts' => array (
						self::HAS_MANY,
						'PromoProduct',
						'promo_id' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'title' => Yii::t ( 'app', 'title' ),
				'description' => Yii::t ( 'app', 'description' ),
				'code' => Yii::t ( 'app', 'code' ),
				'discount' => Yii::t ( 'app', 'discount' ),
				'expiry_date' => Yii::t ( 'app', 'expiry date' ),
				'state_id' => Yii::t ( 'app', 'state' ),
				'type_id' => Yii::t ( 'app', 'type' ),
				'create_time' => Yii::t ( 'app', 'create time' ),
				'create_user_id' => null,
				'createUser' => null,
				'promoProducts' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'title', $this->title, true );
		$criteria->compare ( 'description', $this->description, true );
		$criteria->compare ( 'code', $this->code, true );
		$criteria->compare ( 'discount', $this->discount, true );
		$criteria->compare ( 'expiry_date', $this->expiry_date, true );
		$criteria->compare ( 'state_id', $this->state_id );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}