<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{postage}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Postage".
 *
 * Columns in table "{{postage}}" available as properties of the model,
 * followed by relations of table "{{postage}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $first_item_cost
 * @property integer $additional_item_cost
 * @property integer $custom_price
 * @property integer $state_id
 * @property integer $type_id
 * @property integer $create_user_id
 * @property string $create_time
 * @property string $update_time
 *
 * @property User $createUser
 */
abstract class BasePostage extends ActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
		if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		if ( !isset( $this->update_time )) $this->update_time = new CDbExpression('NOW()');
			}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{postage}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Postage|Postages', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, create_user_id, create_time, update_time,first_item_cost,additional_item_cost', 'required'),
				array('first_item_cost, additional_item_cost', 'required','on'=>'create'),
			array('first_item_cost, additional_item_cost, custom_price, state_id, type_id, create_user_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>256),
			array('first_item_cost, additional_item_cost, custom_price, state_id, type_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, first_item_cost, additional_item_cost, custom_price, state_id, type_id, create_user_id, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'first_item_cost' => Yii::t('app', 'First Item Cost'),
			'additional_item_cost' => Yii::t('app', 'Additional Item Cost'),
			'custom_price' => Yii::t('app', 'Enable Custom Price'),
			'state_id' => Yii::t('app', 'State'),
			'type_id' => Yii::t('app', 'Type'),
			'create_user_id' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'createUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('first_item_cost', $this->first_item_cost);
		$criteria->compare('additional_item_cost', $this->additional_item_cost);
		$criteria->compare('custom_price', $this->custom_price);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}