<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{average_rating}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AverageRating".
 *
 * Columns in table "{{average_rating}}" available as properties of the model,
 * followed by relations of table "{{average_rating}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $average_rating
 * @property string $create_time
 *
 * @property Product $product
 */
abstract class BaseAverageRating extends ActiveRecord {

	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date( 'Y-m-d H:i:s');
		}else{
			}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{average_rating}}';
	}

	public static function label($n = 1) {
			return Yii::t('app', 'Average Rating|Average Ratings', $n);
	}

	public static function representingColumn() {
		return 'average_rating';
	}

	public function rules() {
		return array(
			array('product_id', 'required'),
			array('product_id', 'numerical', 'integerOnly'=>true),
			array('average_rating', 'length', 'max'=>255),
			array('create_time', 'safe'),
			array('average_rating, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, average_rating, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'average_rating' => Yii::t('app', 'average rating'),
			'create_time' => Yii::t('app', 'create time'),
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('average_rating', $this->average_rating, true);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}