<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{temp_file}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TempFile".
 *
 * Columns in table "{{temp_file}}" available as properties of the model,
 * followed by relations of table "{{temp_file}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $image_path
 * @property integer $state_id
 * @property integer $product_id
 * @property integer $create_user_id
 * @property string $create_time
 *
 * @property User $createUser
 */
abstract class BaseTempFile extends ActiveRecord {

	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		}else{
		}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{temp_file}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TempFile|TempFiles', $n);
	}

	public static function representingColumn() {
		return 'image_path';
	}

	public function rules() {
		return array(
				array('image_path, create_user_id', 'required'),
				array('state_id, product_id, create_user_id, order_no,type_id', 'numerical','integerOnly'=>true),
				array('image_path', 'length', 'max'=>1024),
				array('create_time', 'safe'),
				array('state_id, product_id, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
				array('id, image_path, state_id, product_id,order_no,create_user_id,type_id,create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
				'id' => Yii::t('app', 'ID'),
				'image_path' => Yii::t('app', 'Image Path'),
				'state_id' => Yii::t('app', 'State'),
				'product_id' => Yii::t('app', 'Product'),
				'type_id' => Yii::t('app', 'Type'),
				'create_user_id' => null,
				'create_time' => Yii::t('app', 'Create Time'),
				'createUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('image_path', $this->image_path, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
		));
	}
}