<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{order_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderItem".
 *
 * Columns in table "{{order_item}}" available as properties of the model,
 * followed by relations of table "{{order_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $create_user_id
 * @property string $sku
 * @property string $quantity
 * @property string $amount
 * @property integer $type_id
 * @property integer $state_id
 * @property string $ship_time
 * @property string $create_time
 * @property string $update_time
 *
 * @property User $createUser
 * @property Order $order
 */
abstract class BaseOrderItem extends ActiveRecord {
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Published",
				"Archive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{order_item}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'OrderItem|OrderItems', $n );
	}
	public static function representingColumn() {
		return 'ship_time';
	}
	public function rules() {
		return array (
				array (
						'order_id, product_id, create_user_id, create_time',
						'required' 
				),
				array (
						'order_id, product_id, create_user_id, type_id, state_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'sku, quantity, amount',
						'length',
						'max' => 32 
				),
				array (
						'sku, quantity, amount, type_id, state_id',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, order_id, product_id, create_user_id, sku, quantity, amount, type_id, state_id, ship_time, create_time, update_time',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'order' => array (
						self::BELONGS_TO,
						'Order',
						'order_id' 
				),
				'product' => array (
						self::BELONGS_TO,
						'Product',
						'product_id' 
				) ,
				'color' => array (
						self::BELONGS_TO,
						'Color',
						'color_id'
				), // get related product color if any.
				'size' => array (
						self::BELONGS_TO,
						'Size',
						'size_id'
				),
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'order_id' => null,
				'product_id' => Yii::t ( 'app', 'product' ),
				'create_user_id' => null,
				'sku' => Yii::t ( 'app', 'sku' ),
				'quantity' => Yii::t ( 'app', 'quantity' ),
				'amount' => Yii::t ( 'app', 'amount' ),
				'type_id' => Yii::t ( 'app', 'type' ),
				'state_id' => Yii::t ( 'app', 'state' ),
				'ship_time' => Yii::t ( 'app', 'ship time' ),
				'create_time' => Yii::t ( 'app', 'create time' ),
				'update_time' => Yii::t ( 'app', 'update time' ),
				'createUser' => null,
				'order' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'order_id', $this->order_id );
		$criteria->compare ( 'product_id', $this->product_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'sku', $this->sku, true );
		$criteria->compare ( 'quantity', $this->quantity, true );
		$criteria->compare ( 'amount', $this->amount, true );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'state_id', $this->state_id );
		$criteria->compare ( 'ship_time', $this->ship_time, true );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'update_time', $this->update_time, true );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}