<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{wish_list}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WishList".
 *
 * Columns in table "{{wish_list}}" available as properties of the model,
 * followed by relations of table "{{wish_list}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $model_id
 * @property integer $type_id * @property integer $state_id
 * @property integer $create_user_id
 * @property string $create_time
 *
 * @property User $createUser
 */
abstract class BaseWishList extends ActiveRecord {
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3"
		);
		if ($id == null)
			return $list;
			if (is_numeric ( $id ))
				return $list [$id];
				return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{wish_list}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'wishList|wishLists', $n );
	}
	public static function representingColumn() {
		return 'create_time';
	}
	public function rules() {
		return array (
				array (
						'model_id, type_id, create_user_id',
						'required' 
				),
				array (
						'model_id, type_id,state_id,create_user_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'create_time',
						'safe' 
				),
				array (
						'create_time',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, model_id, type_id, create_user_id, create_time',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'product' => array (
						self::BELONGS_TO,
						'Product',
						'model_id' 
				),
				'blog' => array (
						self::BELONGS_TO,
						'Blog',
						'model_id' 
				),
				'store' => array (
						self::BELONGS_TO,
						'Company',
						'model_id' 
				),
				'emporium' => array (
						self::BELONGS_TO,
						'Emporium',
						'model_id' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'model_id' => Yii::t ( 'app', 'model' ),
				'type_id' => Yii::t ( 'app', 'type' ),
				'create_user_id' => null,
				'create_time' => Yii::t ( 'app', 'create time' ),
				'createUser' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'model_id', $this->model_id );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}