<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{mailing}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mailing".
 *
 * Columns in table "{{mailing}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $subject
 * @property string $content
 * @property string $queue
 * @property string $sent
 * @property integer $type_id
 * @property integer $state_id
 * @property string $create_time
 * @property string $finishedOn
 *
 */
abstract class BaseMailing extends ActiveRecord {
	const TYPE_NEWSLETTER = 1;
	const STATE_QUEUE = 1;
	const STATE_INPROGRESS = 2;
	const STATE_COMPLETED = 3;
	public static function getTypeOptions($id = null) {
		$list = array (
				"News Letter",
		);
		if ($id === null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id % count ( $list )];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Queue",
				"InProgress",
				"Completed"
		);
		if ($id === null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id % count ( $list )];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = date ( 'Y-m-d H:i:s' );
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{mailing}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'Mailing|Mailings', $n );
	}
	public static function representingColumn() {
		return 'subject';
	}
	public function rules() {
		return array (
				array (
						'subject,content,  queue, type_id, state_id, create_time',
						'required' 
				),
				array (
						'type_id, state_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'subject',
						'length',
						'max' => 255 
				),
				array (
						'sent',
						'safe' 
				),
				array (
						'sent',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, subject, content, queue, sent, type_id, state_id, create_time, finishedOn',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array ();
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'subject' => Yii::t ( 'app', 'subject' ),
				'content' => Yii::t ( 'app', 'content' ),
				'queue' => Yii::t ( 'app', 'queue' ),
				'sent' => Yii::t ( 'app', 'sent' ),
				'type_id' => Yii::t ( 'app', 'type' ),
				'state_id' => Yii::t ( 'app', 'state' ),
				'create_time' => Yii::t ( 'app', 'create time' ),
				'finishedOn' => Yii::t ( 'app', 'finished on' ) 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'subject', $this->subject, true );
		$criteria->compare ( 'content', $this->content, true );
		$criteria->compare ( 'queue', $this->queue, true );
		$criteria->compare ( 'sent', $this->sent, true );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'state_id', $this->state_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'finishedOn', $this->finishedOn, true );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}