<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{slider_image}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SliderImage".
 *
 * Columns in table "{{slider_image}}" available as properties of the model,
 * followed by relations of table "{{slider_image}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $slider_image
 * @property integer $store_id
 * @property integer $type_id
 * @property integer $state_id
 * @property string $create_time
 * @property integer $create_user_id
 *
 * @property User $createUser
 */
abstract class BaseSliderImage extends ActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}

	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;
		}else{
		}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{slider_image}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SliderImage|SliderImages', $n);
	}

	public static function representingColumn() {
		return 'slider_image';
	}

	public function rules() {
		return array(
				array('slider_image, create_user_id', 'required'),
				array('store_id, type_id,order_no, state_id, create_user_id', 'numerical', 'integerOnly'=>true),
				array('title', 'length', 'max'=>128),
				array('slider_image', 'length', 'max'=>1024),
				array('create_time', 'safe'),
				array('title, store_id, type_id, state_id, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
				array('id, title, slider_image, store_id, type_id, state_id, create_time, create_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
				'id' => Yii::t('app', 'ID'),
				'title' => Yii::t('app', 'Title'),
				'slider_image' => Yii::t('app', 'Slider Image'),
				'store_id' => Yii::t('app', 'Store'),
				'type_id' => Yii::t('app', 'Type'),
				'state_id' => Yii::t('app', 'State'),
				'order_no' => Yii::t('app', 'Order No'),
				'create_time' => Yii::t('app', 'Create Time'),
				'create_user_id' => null,
				'createUser' => null,
		);
	}

	public function search()
	{
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('slider_image', $this->slider_image, true);
		$criteria->compare('store_id', $this->store_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);

		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
		));
	}
}