<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{rating}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rating".
 *
 * Columns in table "{{rating}}" available as properties of the model,
 * followed by relations of table "{{rating}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $rating
 * @property integer $create_user_id
 * @property string $create_time
 *
 * @property User $createUser
 * @property Product $product
 */
abstract class BaseRating extends ActiveRecord {

	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
		if ( !isset( $this->create_time )) $this->create_time = date( 'Y-m-d H:i:s');
		}else{
				}
		return parent::beforeValidate();
	}
	
	

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{rating}}';
	}

	public static function label($n = 1) {
			return Yii::t('app', 'rating|ratings', $n);
	}

	public static function representingColumn() {
		return 'rating';
	}

	public function rules() {
		return array(
			array('product_id, rating, create_user_id', 'required'),
			array('product_id, create_user_id', 'numerical', 'integerOnly'=>true),
			array('rating', 'length', 'max'=>255),
			array('create_time', 'safe'),
			array('create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, rating, create_user_id, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'rating' => Yii::t('app', 'rating'),
			'create_user_id' => null,
			'create_time' => Yii::t('app', 'create time'),
			'createUser' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}