<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{product_image}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductImage".
 *
 * Columns in table "{{product_image}}" available as properties of the model,
 * followed by relations of table "{{product_image}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $image_path
 * @property string $type_id
 * @property integer $state_id
 * @property integer $create_user_id
 * @property string $create_time
 *
 * @property User $createUser
 */
abstract class BaseProductImage extends ActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
		if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_image}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductImage|ProductImages', $n);
	}

	public static function representingColumn() {
		return 'image_path';
	}

	public function rules() {
		return array(
			array('product_id, image_path, type_id, create_user_id', 'required'),
			array('product_id, state_id, create_user_id,order_no', 'numerical', 'integerOnly'=>true),
			array('image_path', 'length', 'max'=>1024),
			array('type_id', 'length', 'max'=>255),
			array('create_time', 'safe'),
			array('state_id, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, image_path, type_id,order_no, state_id, create_user_id, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => Yii::t('app', 'product'),
			'image_path' => Yii::t('app', 'image path'),
			'type_id' => Yii::t('app', 'type'),
			'state_id' => Yii::t('app', 'state'),
			'create_user_id' => null,
			'create_time' => Yii::t('app', 'create time'),
			'createUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('image_path', $this->image_path, true);
		$criteria->compare('type_id', $this->type_id, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}