<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{setting}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Setting".
 *
 * Columns in table "{{setting}}" available as properties of the model,
 * followed by relations of table "{{setting}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $key
 * @property string $value
 * @property integer $type_id
 * @property integer $create_user_id
 * @property string $create_time
 *
 * @property User $createUser
 */
abstract class BaseSetting extends ActiveRecord {
	const TYPE_TEXT = 0;
	const TYPE_IMAGE = 1;
	public $value2,$value3;
	public static function getTypeOptions($id = null) {
		$list = array (
				"Text",
				"Image",
		);
		if ($id === null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id % count ( $list )];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
			if (! isset ( $this->create_time ))
				$this->create_time = date ( 'Y-m-d H:i:s' );
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{setting}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'setting|settings', $n );
	}
	public static function representingColumn() {
		return 'title';
	}
	public function rules() {
		return array (
				array (
						'key',
						'unique'
				),
				array (
						'title, key, type_id, create_user_id, create_time',
						'required' 
				),
				array (
						'type_id, create_user_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'title, key, value',
						'length',
						'max' => 255 
				),
				array (
						'id, title, key, value, type_id, create_user_id, create_time',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'title' => Yii::t ( 'app', 'title' ),
				'key' => Yii::t ( 'app', 'key' ),
				'value' => Yii::t ( 'app', 'value' ),
				'type_id' => Yii::t ( 'app', 'type' ),
				'create_user_id' => null,
				'create_time' => Yii::t ( 'app', 'create time' ),
				'createUser' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'title', $this->title, true );
		$criteria->compare ( 'key', $this->key, true );
		$criteria->compare ( 'value', $this->value, true );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}