<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{cart_size}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CartSize".
 *
 * Columns in table "{{cart_size}}" available as properties of the model,
 * followed by relations of table "{{cart_size}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $cart_item_id
 * @property integer $size_id
 * @property integer $quantity
 * @property string $amount
 * @property integer $state_id
 * @property integer $type_id
 * @property integer $create_user_id
 * @property string $create_time
 * @property string $update_time
 *
 * @property CartItem $cartItem
 */
abstract class BaseCartSize extends ActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	

	
	
	
	
	
		public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 
	
	
	
	
	
		public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
		if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{cart_size}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CartSize|CartSizes', $n);
	}

	public static function representingColumn() {
		return 'amount';
	}

	public function rules() {
		return array(
			array('size_id, quantity, amount, create_time', 'required'),
			array('cart_item_id, size_id, quantity, state_id, type_id, create_user_id', 'numerical', 'integerOnly'=>true),
			array('amount', 'length', 'max'=>255),
			array('update_time', 'safe'),
			array('cart_item_id, state_id, type_id, create_user_id, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, cart_item_id, size_id, quantity, amount, state_id, type_id, create_user_id, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cartItem' => array(self::BELONGS_TO, 'CartItem', 'cart_item_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cart_item_id' => null,
			'size_id' => Yii::t('app', 'size'),
			'quantity' => Yii::t('app', 'quantity'),
			'amount' => Yii::t('app', 'amount'),
			'state_id' => Yii::t('app', 'state'),
			'type_id' => Yii::t('app', 'type'),
			'create_user_id' => Yii::t('app', 'create user'),
			'create_time' => Yii::t('app', 'create time'),
			'update_time' => Yii::t('app', 'update time'),
			'cartItem' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('cart_item_id', $this->cart_item_id);
		$criteria->compare('size_id', $this->size_id);
		$criteria->compare('quantity', $this->quantity);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}