
<?php $this->widget('booster.widgets.TbGridView', array(
	'id' => 'variant-product-grid',
	'type'=>'bordered condensed striped',
	'selectionChanged'=>"function(id){window.location='" . Yii::app()->createAbsoluteUrl('variantProduct/view') . "/' + $.fn.yiiGridView.getSelection(id);}",
	'dataProvider' => $dataProvider,
	'columns' => array(
		'id',
		'title',
		'sku',
		'store_id',
		'product_code',
		'prod_id',
		/*
		'range',
		'edition',
		'hide_public',
		'large_description',
		'tags',
		'related_items',
		'thumbnail_file',
		'image_file',
		array(
			'name'=>'category_id',
			'value'=>'Html::valueEx($data->category)',
			'filter'=>Html::listDataEx(Category::model()->findAllAttributes(null, true)),
			),
		'size_id',
		'color_id',
		'brand_id',
		'is_sale',
		'feature_site',
		'is_featured',
		'postage_id',
		'view_count',
		'warranty_id',
		'quantity',
		'discount_price',
		'price',
		'is_discount',
		'tax',
		'tax_amount',
		array(
				'name' => 'type_id',
				'value'=>'$data->getTypeOptions($data->type_id)',
				'filter'=>VariantProduct::getTypeOptions(),
				),
		array(
				'name' => 'state_id',
				'value'=>'$data->getStatusOptions($data->state_id)',
				'filter'=>VariantProduct::getStatusOptions(),
				),
		'product_id',
		'rss_id',
		'update_time',
		*/
		array(
			'class' => 'CxButtonColumn',
		),
	),
)); ?>