<?php
// AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Thursday 31st of March 2016 12:42:32 AM

/*
 * !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
// HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------
return array (


		"base_url" => "http://localhost/online-clothing-website-679/online-clothing/user/oauth",


		

		"providers" => array (
				// openid providers
				"OpenID" => array (
						"enabled" => false
				),
				
				"AOL" => array (
						"enabled" => false
				),
				
				"Yahoo" => array (
						"enabled" => false,
						"keys" => array (
								"id" => "",
								"secret" => ""
						)
				),
				
				"Google" => array (
						"enabled" => true,
						"keys"    => array ( "id" => "317002193391-rkbei2h2ff706amcnh7musig6c98itb0.apps.googleusercontent.com", "secret" => "cQbaWA0zxFLXdsLnOkd-E66Y" ),
						"scope"   => "https://www.googleapis.com/auth/userinfo.profile ". // optional
						"https://www.googleapis.com/auth/userinfo.email"   , // optional
				),
				"Facebook" => array (
						"enabled" => true,
						"keys"    => array (
								"id" => "813561615470439",
								"secret" => "e1ac9d21b01bb5b6624c643cb95b5f1e"
								/* "id" => "227439147767690",
								"secret" => "b0fe779039796cbf02b2e17a37b7503f"  */
						),
						/* "scope"   => "email,publish_actions",
						"display" => "",
						'return_scopes' => true */
				),


				"Live" => array (
						"enabled" => false,
						"keys" => array (
								"id" => "",
								"secret" => ""
						)
				),
				
				"MySpace" => array (
						"enabled" => false,
						"keys" => array (
								"key" => "",
								"secret" => ""
						)
				),
				
				"LinkedIn" => array (
						"enabled" => false,
						"keys" => array (
								"key" => "75xtzuuos1cj8h",
								"secret" => "INe7J979aFI5ZjpZ"
						)
				),
				
				"Foursquare" => array (
						"enabled" => false,
						"keys" => array (
								"id" => "",
								"secret" => ""
						)
				)
		),
		"debug_mode" => false,

		"debug_file" => "" 

);
